---
- name: system | read config json
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/_utils/get_config_json.yml"

- name: system | define task-scheduler entries
  vars:
    current_config: "{{ vyos_active_config_json['system']['task-scheduler']['task'] | default({}) }}"
  vyos.vyos.vyos_config:
    match: line
    lines: "{{ lookup('template', './config/system/task-scheduler.j2') }}"
