---
name: "Metadata - Label pull requests"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Label pull requests
    runs-on: ubuntu-20.04
    steps:
      - uses: fuxingloh/multi-labeler@v1 
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/labeler-configuration.yml
